### ISSUE TITLE
关于在 libs安装 遇到的问题？

### ISSUE THREAD

**Issue by hdltzd** [liuI/deepin-wine#1]
在按照执行
cd libs && sudo dpkg -i libjpeg62-turbo_1.5.1-2_i386.deb udis86_1.72-2_i386.deb libjpeg62-turbo_1.5.1-2_i386.deb libldap-2.4-2_2.4.45+dfsg-1ubuntu1.10_i386.deb python-dbus-for-22.04.deb python-gobject_3.26.1-2ubuntu1_all.deb  && sudo apt --fix-broken install
后，发生报错，内容如下
(正在读取数据库 ... 系统当前共安装有 212025 个文件和目录。)
准备解压 libjpeg62-turbo_1.5.1-2_i386.deb  ...
正在解压 libjpeg62-turbo:i386 (1:1.5.1-2) 并覆盖 (1:1.5.1-2) ...
准备解压 udis86_1.72-2_i386.deb  ...
正在解压 udis86:i386 (1.72-2) 并覆盖 (1.72-2) ...
准备解压 libjpeg62-turbo_1.5.1-2_i386.deb  ...
正在解压 libjpeg62-turbo:i386 (1:1.5.1-2) 并覆盖 (1:1.5.1-2) ...
准备解压 libldap-2.4-2_2.4.45+dfsg-1ubuntu1.10_i386.deb  ...
正在解压 libldap-2.4-2:i386 (2.4.45+dfsg-1ubuntu1.10) 并覆盖 (2.4.45+dfsg-1ubuntu1.10) ...
正在选中未选择的软件包 python-dbus:i386。
准备解压 python-dbus-for-22.04.deb  ...
正在解压 python-dbus:i386 (1.2.6-1) ...
正在选中未选择的软件包 python-gobject。
准备解压 python-gobject_3.26.1-2ubuntu1_all.deb  ...
正在解压 python-gobject (3.26.1-2ubuntu1) ...
在这此运行中，软件包 libjpeg62-turbo:i386 有多个副本被解压缩了！
现只配置它一次。
正在设置 libjpeg62-turbo:i386 (1:1.5.1-2) ...
正在设置 udis86:i386 (1.72-2) ...
正在设置 libldap-2.4-2:i386 (2.4.45+dfsg-1ubuntu1.10) ...
dpkg: 依赖关系问题使得 python-dbus:i386 的配置工作不能继续：
 python-dbus:i386 依赖于 python2 (<< 2.8).
 python-dbus:i386 依赖于 python2 (>= 2.7~).
 python-dbus:i386 依赖于 python2:any (<< 2.8).
 python-dbus:i386 依赖于 python2:any (>= 2.7.5-5~).

dpkg: 处理软件包 python-dbus:i386 (--install)时出错：
 依赖关系问题 - 仍未被配置
dpkg: 依赖关系问题使得 python-gobject 的配置工作不能继续：
 python-gobject 依赖于 python-gi (>= 3.26.1-2ubuntu1)；然而：
  未安装软件包 python-gi。
 python-gobject 依赖于 python-gobject-2；然而：
  未安装软件包 python-gobject-2。

dpkg: 处理软件包 python-gobject (--install)时出错：
 依赖关系问题 - 仍未被配置
正在处理用于 libc-bin (2.35-0ubuntu3) 的触发器 ...
在处理时有错误发生：
 python-dbus:i386
 python-gobject

**Comment by liui** [comment]
``` bash
cd libs && sudo dpkg -i libjpeg62-turbo_1.5.1-2_i386.deb udis86_1.72-2_i386.deb libjpeg62-turbo_1.5.1-2_i386.deb libldap-2.4-2_2.4.45+dfsg-1ubuntu1.10_i386.deb python-dbus-for-22.04.deb python-gobject_3.26.1-2ubuntu1_all.deb || sudo apt --fix-broken install
```
多谢问题反馈，替换&&为||，原本后续的--fix-broken是在前一条失败，继续执行，大意了，写反了，已更新readme

**Comment by liui** [comment]
``` bash
cd libs && sudo dpkg -i libjpeg62-turbo_1.5.1-2_i386.deb udis86_1.72-2_i386.deb libjpeg62-turbo_1.5.1-2_i386.deb libldap-2.4-2_2.4.45+dfsg-1ubuntu1.10_i386.deb python-dbus-for-22.04.deb python-gobject_3.26.1-2ubuntu1_all.deb || sudo apt --fix-broken install
```
